print("about to fail")
error("intentional failure")